### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shoka6** [keiliving/ramenRecorder#1]
### frontend
- [x] upload form
- [x] upload logic
- [x] get image logic
- [x] render ramen tile view
- [ ] form style

### backend
- [x] upload image API
- [x] get image API
- [ ] deploy
- [ ] logging
